server:
  port: 8084
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/foo"
    jdbc-url: "jdbc:mysql://localhost:3306/foo"
    username: root
    password: root
  secondary-datasource:
    url: "jdbc:mysql://localhost:3306/bar"
    jdbc-url: "jdbc:mysql://localhost:3306/bar"
    username: root
    password: root

datasource:
  secondary-liquibase:
    liquibase:
      change-log: classpath:/db/changelog/changelog-master-secondary.xml
  primary-liquibase:
    liquibase:
      change-log: classpath:/db/changelog/changelog-master-primary.xml